### ISSUE TITLE
Failed to run this project

### ISSUE THREAD

**Issue by EdmondFrank** [lightsing/crates-mirror-ngx#24]
**Describe the bug**
![image](https://user-images.githubusercontent.com/13914416/109921471-e4f51c80-7cf6-11eb-8cd2-ea6d9fecbcf6.png)

It seems that an error occurred during git rebase

**Environment:**
 - OS:  Ubuntu 18.04 LTS
 - rustc 1.50.0 (cb75ad5db 2021-02-10)
 - cargo version: cargo 1.50.0 (f04e7fab7 2021-02-04)

**Comment by lightsing** [comment]
It seems to be a problem related with `libgit2`.
I need more infomation to locate the error since I cannot reproduce this bug.

**Comment by lightsing** [comment]
I made some changes to get more error details.
Could you run it with `trace` level?
Like this:
```yaml
refresh_rate: 30 seconds
appenders:
  stdout-lineno:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {l:<5} [{T}] {M}(({f}:{L})): {m}{n}"
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {l:<5} [{T}] {M}((...)): {m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  crates_io_cn:
    level: trace
    additive: false
    appenders:
      - stdout-lineno
```
