### ISSUE TITLE
Update custom registry config for cargo-update

### ISSUE THREAD

**Issue by xiashali** [lightsing/crates-mirror-ngx#7]
Since nightly-2019-09-10 due to a Cargo regression (or feature, but it's breaking without a major version bump, so) --registry looks into a different key, requiring this additional stanza to ensure correct updates

Also see
https://crates.io/crates/cargo-update
https://doc.rust-lang.org/cargo/reference/source-replacement.html

**Comment by lightsing** [comment]
[Documentation](https://crates-io.cn/) updated.

```toml
[source.crates-io]
replace-with = "crates-io-cn"

[source.crates-io-cn]
registry = "https://crates-io.cn/crates.io-index"

[registries.crates-io-cn]
index = "https://crates-io.cn/crates.io-index"
```
